name: Run Tests

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bun test
        env:
          MONGO_URL: ${{ secrets.MONGO_URL }}
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
